//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Ads
    /// </summary>
    public partial class Ads
    {
        /// <summary>
        /// 
        /// </summary>
        public int AdsId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AdsName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AdsType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Advertisers { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AdsImage { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AdsFiles { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> AdsPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> AdsDiscount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Balance { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BillingType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> DisplayNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Hits { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Volume { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AdsUrl { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> BuyDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> StartDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> EndDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Season { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PutPage { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string DisplayMode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Sort { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> Shelves { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UnderReason { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AdsCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> AdsStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Ads1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Ads2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Ads3 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Ads4 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Ads5 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> Ads6 { get; set; }
    }
}
