//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Applicants
    /// </summary>
    public partial class Applicants
    {
        public Applicants()
        {
            this.Audition = new HashSet<Audition>();
            this.EntryFlow = new HashSet<EntryFlow>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int ApplicantsId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ApplicantsName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Gender { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Birthdate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Education { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Major { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Mobile { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Resume { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PositionApplication { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ApplicationResult { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> ApplicantsStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Applicants1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Applicants2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Applicants3 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Applicants4 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Applicants5 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> Applicants6 { get; set; }
    
        public virtual ICollection<Audition> Audition { get; set; }
        public virtual ICollection<EntryFlow> EntryFlow { get; set; }
    }
}
