//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Area
    /// </summary>
    public partial class Area
    {
        public Area()
        {
            this.TravelAgency = new HashSet<TravelAgency>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int AreaId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ParentId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AreaNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ChineseName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ChineseAbbreviation { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> TravelAgencyCount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Sort { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsUse { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Display { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string HomeAbroad { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string EnglishName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string EnglishAbbreviation { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LogoFlag { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> AreaStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Area1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Area2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Area3 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Area4 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> Area5 { get; set; }
    
        public virtual ICollection<TravelAgency> TravelAgency { get; set; }
    }
}
