//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Audition
    /// </summary>
    public partial class Audition
    {
        /// <summary>
        /// 
        /// </summary>
        public int AuditionId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ApplicantsId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> InterviewDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> EntryDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string NotPassReson { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string InterviewComments { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Interviewer { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> AuditionStatus { get; set; }
    
        public virtual Applicants Applicants { get; set; }
    }
}
