//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// BookingInformation
    /// </summary>
    public partial class BookingInformation
    {
        /// <summary>
        /// 
        /// </summary>
        public int BookingInforId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> TravelProductId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string InforType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TravelType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Item { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TemplateName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Sort { get; set; }
    
        public virtual TravelProduct TravelProduct { get; set; }
    }
}
