//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// BusinessMan
    /// </summary>
    public partial class BusinessMan
    {
        public BusinessMan()
        {
            this.Favorite = new HashSet<Favorite>();
            this.LeaveMessage = new HashSet<LeaveMessage>();
            this.LineSchedule = new HashSet<LineSchedule>();
            this.Messages = new HashSet<Messages>();
            this.OnlineChat = new HashSet<OnlineChat>();
            this.Orders = new HashSet<Orders>();
            this.RefundWords = new HashSet<RefundWords>();
            this.VisitRecord = new HashSet<VisitRecord>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int BusinessManId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> RetailSalesId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FullName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Pwd { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayPwd { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WeiXin { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Skype { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ValidationCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ValidationCodeSendDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CodeValidPeriod { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Performance { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UseState { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WebUrl { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Fax { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Telphone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MobilePhone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string QQ { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> BusinessManStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string HeadImage { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Role { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsUse { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Gender { get; set; }
    
        public virtual RetailSales RetailSales { get; set; }
        public virtual ICollection<Favorite> Favorite { get; set; }
        public virtual ICollection<LeaveMessage> LeaveMessage { get; set; }
        public virtual ICollection<LineSchedule> LineSchedule { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<OnlineChat> OnlineChat { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<RefundWords> RefundWords { get; set; }
        public virtual ICollection<VisitRecord> VisitRecord { get; set; }
    }
}
