//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// CommonContact
    /// </summary>
    public partial class CommonContact
    {
        public CommonContact()
        {
            this.OrderToCommonContact = new HashSet<OrderToCommonContact>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int CommonContactId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> VisitorId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FullName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Sex { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string IdType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string IdNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MobilePhone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string IDCard { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Passport { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Pass { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsChildren { get; set; }
    
        public virtual Visitor Visitor { get; set; }
        public virtual ICollection<OrderToCommonContact> OrderToCommonContact { get; set; }
    }
}
