//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// ContractApplication
    /// </summary>
    public partial class ContractApplication
    {
        public ContractApplication()
        {
            this.Contract = new HashSet<Contract>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int ContractApplicationId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> TravelAgencyId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> LineId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> DomesticNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> InternationalNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ReturnContractId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> People { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ApplyDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> OutDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ComeDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> TotalAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> AdultAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ChildrenAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Claimant { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string lineName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> ContractApplicationStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> UnitPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string GetType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LinkMan { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Mobile { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SettleRemark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Progress { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ContractApplication1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ContractApplication2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ContractApplication3 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ContractApplication4 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FreeNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> DriveYourselfNumber { get; set; }
    
        public virtual ICollection<Contract> Contract { get; set; }
    }
}
