//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// ContractReturn
    /// </summary>
    public partial class ContractReturn
    {
        public ContractReturn()
        {
            this.Contract = new HashSet<Contract>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int ContractReturnId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> TravelAgencyId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> People { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Adult { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Children { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> OutDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ComeDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> TotalAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> AdultAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ChildrenAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string InternationalDomestic { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LineName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> ContractReturnStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LostContractNos { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ContractReturn1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ContractReturn2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ContractReturn3 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ContractReturn4 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> RetailSalesId { get; set; }
    
        public virtual ICollection<Contract> Contract { get; set; }
        public virtual RetailSales RetailSales { get; set; }
    }
}
