//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Debriefing
    /// </summary>
    public partial class Debriefing
    {
        /// <summary>
        /// 
        /// </summary>
        public int DebriefingId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> TaskId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ReportContent { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Attachment { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Reporter { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ReportTo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShareTo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ReportDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> DebriefingStatus { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
