//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// ExpressList
    /// </summary>
    public partial class ExpressList
    {
        /// <summary>
        /// 
        /// </summary>
        public int ExpressListId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FlowNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Department { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Sender { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SendAddress { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TrackingNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ExpressFee { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remarks { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> ExpressListStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> adddate { get; set; }
    }
}
