//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Favorite
    /// </summary>
    public partial class Favorite
    {
        /// <summary>
        /// 
        /// </summary>
        public int FavoriteId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> BusinessManId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> LineId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FavoriteStatus { get; set; }
    
        public virtual BusinessMan BusinessMan { get; set; }
        public virtual TravelProduct TravelProduct { get; set; }
    }
}
