//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FileCenter
    /// </summary>
    public partial class FileCenter
    {
        /// <summary>
        /// 
        /// </summary>
        public int FileCenterId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FileNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FileName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> DownloadTimes { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FileType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FileSize { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> UploadDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Brief { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Permission { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AllowViewUsers { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AllowViewRoles { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AllowViewDepts { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> FileStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsDel { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsPublic { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FileCenterStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UploadFile { get; set; }
    }
}
