//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FinancialAccounts
    /// </summary>
    public partial class FinancialAccounts
    {
        public FinancialAccounts()
        {
            this.BalanceOfWater = new HashSet<BalanceOfWater>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int FinancialAccountsId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> HeadOfficeId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> CreationDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> InitialBalance { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AccountNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AccountName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BankName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BankAccount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WebBankAccount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WebBankLogo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PaymentInterface { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RedirectionUrl { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ServerNoticeUrl { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Type { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UseState { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FinancialAccountsStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CreateUser { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ForUse { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UseRole { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WhoUse { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Category { get; set; }
    
        public virtual ICollection<BalanceOfWater> BalanceOfWater { get; set; }
    }
}
