//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// FixedAssets
    /// </summary>
    public partial class FixedAssets
    {
        /// <summary>
        /// 
        /// </summary>
        public int FixedAssetsId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FixedAssetsNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ItemName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ItemNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Unit { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> PurchasePrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> TotalSum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Depreciation { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Category { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AffiliatedDepartment { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> AgeLimit { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Property { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> EnableDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remarks { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsScrap { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ScrapDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> FixedAssetsStatus { get; set; }
    }
}
