//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// GroupStage
    /// </summary>
    public partial class GroupStage
    {
        public GroupStage()
        {
            this.Invoice = new HashSet<Invoice>();
            this.LineSchedule = new HashSet<LineSchedule>();
            this.Orders = new HashSet<Orders>();
            this.QueueInfo = new HashSet<QueueInfo>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int GroupStageId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> LineId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> PlanBit { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ApplyBit { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ConfirmationBit { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> OutDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ComeDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> EndRegistration { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ChildrenPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> AdultPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ChildrenTakeoutPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> AdultTakeoutPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> LineSettlementPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string GroupNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PublishState { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> GroupStageStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UnderReason { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> OccupationOverTime { get; set; }
    
        public virtual TravelProduct TravelProduct { get; set; }
        public virtual ICollection<Invoice> Invoice { get; set; }
        public virtual ICollection<LineSchedule> LineSchedule { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<QueueInfo> QueueInfo { get; set; }
    }
}
