//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Hotel
    /// </summary>
    public partial class Hotel
    {
        /// <summary>
        /// 
        /// </summary>
        public int HotelId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Intro { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Price { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string HotelName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Thum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Photo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Star { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Area { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string NearMark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Addres { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string HotelPhoto { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> HotelStatus { get; set; }
    }
}
