//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Invoice
    /// </summary>
    public partial class Invoice
    {
        /// <summary>
        /// 
        /// </summary>
        public int InvoiceId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> GroupStageId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ContractId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> TravelAgencyId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsInvalid { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> TotalAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TickNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ApplyDepartment { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ApplyPerson { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Members { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string InvoiceProperty { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Operator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string GetInvoicePerson { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Source { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string State { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Recipient { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MobilePhone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AmountCapital { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SettlementRemark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FinancialRemark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string InvoiceText { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LineName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string InvoiceType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string InvoiceTitle { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ContractNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string People { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> InvoiceStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> AddDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TravelNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CheckDetails { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CheckPerson { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TravelAgencyName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Progress { get; set; }
    
        public virtual GroupStage GroupStage { get; set; }
        public virtual TravelAgency TravelAgency { get; set; }
    }
}
