//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// LanEmail
    /// </summary>
    public partial class LanEmail
    {
        /// <summary>
        /// 
        /// </summary>
        public int LEId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> EmailType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Recipients { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CC { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BCC { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Content { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Sender { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> SendDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Reader { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ToTrush { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ToDel { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Attachment { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> Status { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> LanEmailStatus { get; set; }
    }
}
