//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Leader
    /// </summary>
    public partial class Leader
    {
        /// <summary>
        /// 
        /// </summary>
        public int LeaderId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LeaderNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LeaderCardNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LeaderName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LeaderSex { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> Birthday { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CardNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> SupplierId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> OnJob { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ValidTill { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> LeaderStatus { get; set; }
    }
}
