//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// LeaveMessage
    /// </summary>
    public partial class LeaveMessage
    {
        /// <summary>
        /// 
        /// </summary>
        public int LeaveMessageId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> BusinessManId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> MessageDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsPublic { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MessagePerson { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MessageContent { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> LeaveMessageStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsReply { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ReplyWords { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Replier { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ReplyDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> TravelAgencyId { get; set; }
    
        public virtual BusinessMan BusinessMan { get; set; }
        public virtual TravelAgency TravelAgency { get; set; }
    }
}
