//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// LoginLog
    /// </summary>
    public partial class LoginLog
    {
        /// <summary>
        /// 
        /// </summary>
        public int LoginLogId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LoginName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> LoginDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LoginIP { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string VisitUrl { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ToOperate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> LoginLogStatus { get; set; }
    }
}
