//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// News
    /// </summary>
    public partial class News
    {
        /// <summary>
        /// 
        /// </summary>
        public int NewsId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Title { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string NewsType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string NewsContent { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Publisher { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Sendee { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RecieveDept { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RecieveRole { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RecieveForm { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ReaderAdvice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Reader { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsTop { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Enclosure { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> NewsStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> PublishDate { get; set; }
    }
}
