//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Notice
    /// </summary>
    public partial class Notice
    {
        /// <summary>
        /// 
        /// </summary>
        public int NoticeId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> PostDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MessageTitle { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ReceivePeople { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ReleasePeople { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreMessage { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BusinessMessage { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> NoticeStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WhoRead { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WhoDel { get; set; }
    }
}
