//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Orders
    /// </summary>
    public partial class Orders
    {
        public Orders()
        {
            this.OrderDetails = new HashSet<OrderDetails>();
            this.OrderToCommonContact = new HashSet<OrderToCommonContact>();
            this.PayToSupplier = new HashSet<PayToSupplier>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int OrdersId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> GroupStageId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> LineId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> SupplierId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> VisitorId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> PayDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> OrderDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> PayTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> RefundState { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> CollectionState { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> OrderState { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> OccupyingState { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> PayAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RefundAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Receivable { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Received { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Adjustment { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Uncollected { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> FinancialInfo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string OrderNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AllLineCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string OrderType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> OrderStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> AdultNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ChildrenNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> BusinessManId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> PayState { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> TradePrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> PriceUpdate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string OrderRemark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ApplyRefundDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> LineScheduleId { get; set; }
    
        public virtual BusinessMan BusinessMan { get; set; }
        public virtual GroupStage GroupStage { get; set; }
        public virtual LineSchedule LineSchedule { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual TravelProduct TravelProduct { get; set; }
        public virtual Visitor Visitor { get; set; }
        public virtual ICollection<OrderToCommonContact> OrderToCommonContact { get; set; }
        public virtual ICollection<PayToSupplier> PayToSupplier { get; set; }
    }
}
