//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// OrderToCommonContact
    /// </summary>
    public partial class OrderToCommonContact
    {
        /// <summary>
        /// 
        /// </summary>
        public int OrderToId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> CommonContactId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> OrdersId { get; set; }
    
        public virtual CommonContact CommonContact { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
