//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// OrderDetails
    /// </summary>
    public partial class OrderDetails
    {
        /// <summary>
        /// 
        /// </summary>
        public int OrderDetailsId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int OrderId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int VisitorId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string IsMaster { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsChildren { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
