//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// OtherSupply
    /// </summary>
    public partial class OtherSupply
    {
        /// <summary>
        /// 
        /// </summary>
        public int OtherSupplyId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> EpiryDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> AddDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string OtherName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TargetCity { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Direction { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AddUser { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string State { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> OtherSupplyStatus { get; set; }
    }
}
