//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Para
    /// </summary>
    public partial class Para
    {
        /// <summary>
        /// 
        /// </summary>
        public int ParaId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PValue { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ParentId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> ParaStatus { get; set; }
    }
}
