//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Payment
    /// </summary>
    public partial class Payment
    {
        public Payment()
        {
            this.PayToSupplier = new HashSet<PayToSupplier>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int PaymentId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> LineId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> PeopleNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ApplyDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> OutDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ComeDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> PayDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> PayTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> PayAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayCategory { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Company { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayObject { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayMethod { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string State { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string DeptManager { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string GeneralManager { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Currency { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string DocumentNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ApplicantUser { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AmountCapital { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayInfo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PaySubject { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TabUser { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SettlementSigned { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FinancialSignature { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> PaymentStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string OrderNos { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SuppliersNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LinkMan { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Mobile { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PaymentRemark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Status { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayDept { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CommissionIncomeAmt { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> OrderAmt { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string VoucherNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PassCheck { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Usage { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LineName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BackName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AccountName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AccountNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FileName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> SupplierId { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<PayToSupplier> PayToSupplier { get; set; }
    }
}
