//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// PCArea
    /// </summary>
    public partial class PCArea
    {
        public PCArea()
        {
            this.PCArea1 = new HashSet<PCArea>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public string ID { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AreaName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ParentId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShortName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LevelType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CityCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ZipCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Pinyin { get; set; }
    
        public virtual ICollection<PCArea> PCArea1 { get; set; }
        public virtual PCArea PCArea2 { get; set; }
    }
}
