//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// QueueInfo
    /// </summary>
    public partial class QueueInfo
    {
        /// <summary>
        /// 
        /// </summary>
        public int QueueInfoId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> VisitorId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> GroupStageId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> SurplusVacancy { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> QueuePeople { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PlanNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> QueueInfoStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> BusinessManId { get; set; }
    
        public virtual GroupStage GroupStage { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
