//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Receivables
    /// </summary>
    public partial class Receivables
    {
        /// <summary>
        /// 
        /// </summary>
        public int ReceivablesId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ApplyDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> BorrowedDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> BorrowedAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ReceiptsNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Company { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ReceiptType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Currency { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AmountCapital { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SettlementAudit { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string State { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string DeptManager { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FinancialAudit { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FinancialManager { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string GeneralManager { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MoneyType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string DocumentNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayeeInformation { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PaymentType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ReceiptsRemark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PaymentInformation { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TabUser { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SettlementSigned { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> ReceivablesStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LinkMan { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Moblie { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayInfo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FromDept { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayFor { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string KeyNo1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string KeyNo2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string VoucherNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SupplierNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> PrintTimes { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TicketPic { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> isCheck { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string gid { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayItem { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IfUsed { get; set; }
    }
}
