//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Recharge
    /// </summary>
    public partial class Recharge
    {
        /// <summary>
        /// 
        /// </summary>
        public int RechargeId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> RechargeDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ValidPeriod { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RechargeAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RechargeRecordCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ValidationCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MobilePhone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Operator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> RechargeStatus { get; set; }
    }
}
