//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// RecruitmentApplication
    /// </summary>
    public partial class RecruitmentApplication
    {
        /// <summary>
        /// 
        /// </summary>
        public int RecruitmentApplicationId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RecruitNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RecruitPostion { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RecruitDept { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Applicant { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RecruitReason { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RecruitConditions { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ApplicationDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> RecruitNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string QualityRequirements { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string JobResponsibilities { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string JobRequirements { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string HROpinion { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RecruitmentOpinion { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string GeneralManagerOpinion { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Progress { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> RecruitmentApplicationStatus { get; set; }
    }
}
