//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// RecruitmentEmployee
    /// </summary>
    public partial class RecruitmentEmployee
    {
        /// <summary>
        /// 
        /// </summary>
        public int RecruitmentEmployeeId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StaffNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> EntryDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ConfirmationDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ContractStartDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ContractEndDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WorkDept { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Position { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PositiveComments { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Comments { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> DepartureDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> EmploymentStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string EmploymentContract { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> RecruitmentEmployeeStatus { get; set; }
    }
}
