//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Refund
    /// </summary>
    public partial class Refund
    {
        public Refund()
        {
            this.RefundWords = new HashSet<RefundWords>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int RefundId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> SupplierId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ApplyDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> RefundDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> RefundState { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RefundAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Penalty { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> OtherCosts { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string OrderNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RefundSerialNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RefundReason { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RefundInro { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UploadVoucher { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Applicant { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Progress { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> RefundStatus { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<RefundWords> RefundWords { get; set; }
    }
}
