//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// RefundWords
    /// </summary>
    public partial class RefundWords
    {
        /// <summary>
        /// 
        /// </summary>
        public int RefundWordsId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> BusinessManId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> VisitorId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> RefundId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> SupplierContactId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> PostDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> RecoveryDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CustomerMessage { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RecoveryMessage { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> RefundWordsStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UploadVoucher { get; set; }
    
        public virtual BusinessMan BusinessMan { get; set; }
        public virtual Refund Refund { get; set; }
        public virtual SupplierContact SupplierContact { get; set; }
        public virtual Visitor Visitor { get; set; }
    }
}
