//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// ReminderFee
    /// </summary>
    public partial class ReminderFee
    {
        /// <summary>
        /// 
        /// </summary>
        public int ReminderFeeId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Store { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string EmpName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PadMonth { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> PadTotal { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ShouldPadMonth { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ShouldPadTotal { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Comments { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> ReminderFeeStatus { get; set; }
    }
}
