//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// RetailSales
    /// </summary>
    public partial class RetailSales
    {
        public RetailSales()
        {
            this.BusinessMan = new HashSet<BusinessMan>();
            this.ContractReturn = new HashSet<ContractReturn>();
            this.Employee = new HashSet<Employee>();
            this.SetEmployeeSalary = new HashSet<SetEmployeeSalary>();
            this.TimeBucketRecord = new HashSet<TimeBucketRecord>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int RetailSalesId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> AmountAccounts { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> AccountAmount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> CostExpense { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Province { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string City { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string County { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Intro { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string State { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Contacts { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MobilePhone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BankName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FullName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BankAccount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AddUser { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> RetailSalesStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ExpressFee { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> BillingRates { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> NotAvailableBalance { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> LimitContractNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> UnReturnNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> ApplyContractNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
    
        public virtual ICollection<BusinessMan> BusinessMan { get; set; }
        public virtual ICollection<ContractReturn> ContractReturn { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<SetEmployeeSalary> SetEmployeeSalary { get; set; }
        public virtual ICollection<TimeBucketRecord> TimeBucketRecord { get; set; }
    }
}
