//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// SignContract
    /// </summary>
    public partial class SignContract
    {
        /// <summary>
        /// 
        /// </summary>
        public int SignContractId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> SupplierId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> SignStartDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> SignEndDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string State { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> PeriodOfValidity { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> SignContractStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Attachment { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
    
        public virtual Supplier Supplier { get; set; }
    }
}
