//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// SocialSecurity
    /// </summary>
    public partial class SocialSecurity
    {
        /// <summary>
        /// 
        /// </summary>
        public int SocialSecurityId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> EmployeeId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> AddWordDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ApprovalDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Wage { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string InsuranceType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string HealthCareReason { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FourInsurance { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Prompt { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Personally { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BackUnitName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RuralType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SpecialMark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ContactName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ContactTelephone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WorkPermitCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BankName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BankAccount { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MedicalInsuranceCategories { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MedicalInstitutions1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MedicalInstitutions2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MedicalInstitutions3 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MedicalInstitutions4 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MedicalInstitutions5 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StaffCategories { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string DistrictCounty { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ZipCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MailAddress { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string GetBillWay { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> SocialSecurityStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
