//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// SocialSecurityInto
    /// </summary>
    public partial class SocialSecurityInto
    {
        /// <summary>
        /// 
        /// </summary>
        public int SocialSecurityIntoId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> DeclarationWage { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AddReason { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StaffCategories { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MedicalInsuranceCategories { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RuralType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AddInsuranceType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WorkPermitCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> SocialSecurityIntoStatus { get; set; }
    }
}
