//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// SupplierContact
    /// </summary>
    public partial class SupplierContact
    {
        public SupplierContact()
        {
            this.OnlineChat = new HashSet<OnlineChat>();
            this.RefundWords = new HashSet<RefundWords>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int SupplierContactId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> SupplierId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FullName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Tel1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Tel2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Fax { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MobilePhone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string QQ { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WeiXinNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> SupplierContactStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsUse { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Position { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LoginName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Password { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayPass { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MsgAuthCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> MsgAuthCodeSendDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string HeadImage { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Gender { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WorkArea { get; set; }
    
        public virtual ICollection<OnlineChat> OnlineChat { get; set; }
        public virtual ICollection<RefundWords> RefundWords { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
