//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Task
    /// </summary>
    public partial class Task
    {
        public Task()
        {
            this.Debriefing = new HashSet<Debriefing>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int TaskId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TaskTitle { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TaskContent { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Publisher { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Executor { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string InfoCommunication { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Progress { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Completion { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CurrentStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> AllocatedDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> StartTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> EndTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AllocationStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsFeedback { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> FeedbackDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TaskInstructions { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> TaskStatus { get; set; }
    
        public virtual ICollection<Debriefing> Debriefing { get; set; }
    }
}
