//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// TransactionFlow
    /// </summary>
    public partial class TransactionFlow
    {
        /// <summary>
        /// 
        /// </summary>
        public int TransactionFlowId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> CreateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Revenue { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Spending { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> AccountBalance { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SerialNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Department { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string DocumentNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UseOf { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PayInfo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Object { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Attn { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> TransactionFlowStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ClientType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AccountType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SupplierNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string OrderNos { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TransactionFlow1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TransactionFlow2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TransactionFlow3 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> TransactionFlow4 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> TransactionFlow5 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> TransactionFlow6 { get; set; }
    }
}
