//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// TravelProduct
    /// </summary>
    public partial class TravelProduct
    {
        public TravelProduct()
        {
            this.BookingInformation = new HashSet<BookingInformation>();
            this.Favorite = new HashSet<Favorite>();
            this.GroupStage = new HashSet<GroupStage>();
            this.LineItinerary = new HashSet<LineItinerary>();
            this.Orders = new HashSet<Orders>();
            this.Travel = new HashSet<Travel>();
            this.TravelFee = new HashSet<TravelFee>();
            this.Visa = new HashSet<Visa>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int TravelProductId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TravelInformation { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> SupplierId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> TravelDays { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> AdvanceDays { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> CollectionNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> OccupyingNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> LowestPriceDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> LastGroupDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> AddDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsAddBack { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsConfirmation { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ChildrenFare { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> AdultFare { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> LowestPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LineName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LineType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LineProp { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string DepartureCity { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ObjectiveCity { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TrafficType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TouristSpots { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Departure { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ReturnTraffic { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PlayType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Direction { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AddPeople { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LineLevel { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string HotelRating { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PriceRange { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SuitablepPeople { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MealStandards1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MealStandards2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LineFeatures { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> TravelProductStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LineNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string RecommendedReason { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UnderReason { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> Shelves { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> StraightPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AuditOpinion { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string DomesticInternational { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TravelEssentials { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LineKeyWords { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> IsModel { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TravelVisa { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> TravelNight { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ChildrenRemark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AdultRemark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> EntireSingleRoom { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> SpecialCrowdSurcharge { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> DiscountTicket { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> SelfCheck { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RemovalTour { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> OldSurcharge { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ChildrenSurcharge { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ChildrenWithoutBed { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> SpecialRegion { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> SpecialAge { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ForeignNationality { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> QuchengZili { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> HuichengZili { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> DocumentsFree { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ChildrenAccountForBed { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> AdmissionTicket { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RoundtripTickets { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> ChildrenPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> AdultPrice { get; set; }
    
        public virtual ICollection<BookingInformation> BookingInformation { get; set; }
        public virtual ICollection<Favorite> Favorite { get; set; }
        public virtual ICollection<GroupStage> GroupStage { get; set; }
        public virtual ICollection<LineItinerary> LineItinerary { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Travel> Travel { get; set; }
        public virtual ICollection<TravelFee> TravelFee { get; set; }
        public virtual ICollection<Visa> Visa { get; set; }
    }
}
