//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Travel
    /// </summary>
    public partial class Travel
    {
        /// <summary>
        /// 
        /// </summary>
        public int TravelId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> LineId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> NumberOfDays { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Total { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Remainder { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> CollegeDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> TradePrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> RecommendedPrice { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> TravelStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TravelNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string LineNumber { get; set; }
    
        public virtual TravelProduct TravelProduct { get; set; }
    }
}
