//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// UseChapterFlow
    /// </summary>
    public partial class UseChapterFlow
    {
        /// <summary>
        /// 
        /// </summary>
        public int UseChapterFlowId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FlowNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Department { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ChapterName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SealType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> SealNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> CopiesNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> BorrowDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> ReturnDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Reason { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Operator { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> UseDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string DeptApproval { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string GeneralManagerApproval { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Applicant { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> ApprovalStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Progress { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsReturn { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> UseChapterFlowStatus { get; set; }
    }
}
