//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Visa
    /// </summary>
    public partial class Visa
    {
        /// <summary>
        /// 
        /// </summary>
        public int VisaId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int TravelProductId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string VisaName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string VisaRequire { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string VisaDocuments { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> IsTitle { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string TemplateName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Sort { get; set; }
    
        public virtual TravelProduct TravelProduct { get; set; }
    }
}
