//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// Visitor
    /// </summary>
    public partial class Visitor
    {
        public Visitor()
        {
            this.CommonContact = new HashSet<CommonContact>();
            this.OrderDetails = new HashSet<OrderDetails>();
            this.Orders = new HashSet<Orders>();
            this.QueueInfo = new HashSet<QueueInfo>();
            this.RefundWords = new HashSet<RefundWords>();
        }
    
        /// <summary>
        /// 
        /// </summary>
        public int VisitorId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FullName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string CustomerType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Sex { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string IdType { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string IdNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remark { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Relationship { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AstProvince { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AstCity { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AstCounty { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AssistAddress { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AssistTelphone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AssistMobilePhone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MobilePhone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Province { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string City { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string County { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Address { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string IDCard { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Passport { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Pass { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AssistFullName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Credit { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string UserName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Pwd { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Email { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string QQ { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Telphone { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> VisitorStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> Birthday { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string IsMaster { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Visitor1 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Visitor2 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Visitor3 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> Visitor4 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<decimal> Visitor5 { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> Visitor6 { get; set; }
    
        public virtual ICollection<CommonContact> CommonContact { get; set; }
        public virtual ICollection<OrderDetails> OrderDetails { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<QueueInfo> QueueInfo { get; set; }
        public virtual ICollection<RefundWords> RefundWords { get; set; }
    }
}
