//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// VisitRecord
    /// </summary>
    public partial class VisitRecord
    {
        /// <summary>
        /// 
        /// </summary>
        public int VisitRecordId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> BusinessManId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> VisitDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string StoreNumber { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Ip { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> VisitRecordStatus { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> TravelAgencyId { get; set; }
    
        public virtual BusinessMan BusinessMan { get; set; }
        public virtual TravelAgency TravelAgency { get; set; }
    }
}
