//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODEL
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// WorkPlan
    /// </summary>
    public partial class WorkPlan
    {
        /// <summary>
        /// 
        /// </summary>
        public int WorkPlanId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> PlanDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MyWorkPlan { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string PlanTitle { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string SelfInspectionWork { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string WorkContent { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AgencyWork { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AuxiliaryWork { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string AllowView { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> UpdateDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Annex { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<int> AlertTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Implementer { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<System.DateTime> SettingTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public Nullable<bool> WorkPlanStatus { get; set; }
    }
}
